(function(){
  'use strict';
  var R=window.DailyRules,charts=window.CHARTS||[],KEY='chartarena_challenge_v1:',REWARDS='chartarena_rewards_v1',ACTIVE='chartarena_challenge_active_v1';
  var date=R.day(),attempt=null,practice=false,pick=null,index=0,reveal=0,revealing=false,busy=false,db=null,uid=null,cloud=false,closed=false;
  var $=function(id){return document.getElementById(id);};
  function read(key){try{return JSON.parse(localStorage.getItem(key));}catch(e){return null;}}
  function write(key,value){localStorage.setItem(key,JSON.stringify(value));}
  var activeDate=read(ACTIVE),activeAttempt=activeDate&&read(KEY+activeDate);
  date=R.resumeDate(date,activeAttempt);
  var hub=read('chartarena_hub_v1')||{},nick=String(hub.nick||'도전자').slice(0,12),character=hub.ch||(hub.equip&&hub.equip.ch);
  $('dailyAvatar').src='assets/'+(/^hu([0-9]|1[0-6])$/.test(character)?character:'hu0')+'.png?v=7';
  function status(text){$('dailyStatus').textContent=text;}
  function lock(name,fn){return navigator.locks?navigator.locks.request(name,fn):Promise.resolve().then(fn);}
  function timeout(promise,ms){return new Promise(function(resolve,reject){var t=setTimeout(function(){reject(new Error('서버 응답이 지연되고 있습니다.'));},ms||10000);promise.then(function(x){clearTimeout(t);resolve(x);},function(e){clearTimeout(t);reject(e);});});}
  function currentChart(){return attempt&&charts.find(function(c){return c.id===attempt.ids[index];});}
  function reward(){return lock(REWARDS,function(){var r=R.rewards(read(REWARDS),attempt.date);write(REWARDS,r);renderRewards();});}
  function renderRewards(){var r=read(REWARDS)||{days:[],frame:'none',pose:'none',unlockedFrames:['none'],unlockedPoses:['none']};$('dailyRewardStatus').textContent=(r.days||[]).length+'일 도전 완료';[['dailyFrames','frame',r.unlockedFrames||['none'],{none:'기본',blue:'블루',violet:'바이올렛',gold:'골드'}],['dailyPoses','pose',r.unlockedPoses||['none'],{none:'기본',salute:'인사',celebrate:'승리'}]].forEach(function(group){var el=$(group[0]);el.replaceChildren();group[2].forEach(function(value){var b=document.createElement('button');b.type='button';b.textContent=group[3][value];b.setAttribute('aria-pressed',String(r[group[1]]===value));b.onclick=function(){lock(REWARDS,function(){var latest=read(REWARDS)||r;latest[group[1]]=value;write(REWARDS,latest);renderRewards();});};el.appendChild(b);});});$('dailyPortrait').dataset.frame=r.frame;$('dailyPortrait').dataset.pose=r.pose;document.documentElement.dataset.rewardFrame=r.frame;document.documentElement.dataset.rewardPose=r.pose;}
  function draw(){var c=currentChart();if(!c)return;var canvas=$('dailyCanvas'),rect=canvas.getBoundingClientRect();if(!rect.width)return;var dpr=Math.min(window.devicePixelRatio||1,2),w=rect.width,h=rect.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);var ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);ctx.fillStyle='#0c162a';ctx.fillRect(0,0,w,h);var start=Math.max(0,c.vis-40),end=c.vis+reveal,visible=c.cs.slice(start,end),min=Math.min.apply(null,visible.map(function(x){return x[2];})),max=Math.max.apply(null,visible.map(function(x){return x[1];})),pad=(max-min)*.12||1;min-=pad;max+=pad;var left=12,right=54,top=20,bottom=32,total=c.cs.length-start,cw=(w-left-right)/total;function y(v){return top+(max-v)/(max-min)*(h-top-bottom);}ctx.font='11px system-ui';for(var i=0;i<=4;i++){var v=min+(max-min)*i/4,yy=y(v);ctx.strokeStyle='#23334c';ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillStyle='#9bb3d5';ctx.fillText(v.toFixed(v<10?2:1),w-right+6,yy+4);}visible.forEach(function(candle,i){var x=left+(i+.5)*cw;ctx.strokeStyle=ctx.fillStyle=candle[3]>=candle[0]?'#ff6882':'#4e9bff';ctx.beginPath();ctx.moveTo(x,y(candle[1]));ctx.lineTo(x,y(candle[2]));ctx.stroke();ctx.fillRect(x-Math.max(1,cw*.32),Math.min(y(candle[0]),y(candle[3])),Math.max(2,cw*.64),Math.max(1,Math.abs(y(candle[0])-y(candle[3]))));});var boundary=left+(c.vis-start)*cw;ctx.strokeStyle='#a8bbd4';ctx.setLineDash([4,4]);ctx.beginPath();ctx.moveTo(boundary,top);ctx.lineTo(boundary,h-bottom);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#b8c9e2';ctx.fillText('현재',Math.max(left,boundary-12),h-12);if(!reveal){ctx.fillStyle='#abc1e0';ctx.textAlign='center';ctx.fillText('다음 구간',boundary+(w-right-boundary)/2,h/2);ctx.textAlign='left';}canvas.setAttribute('aria-label','차트 '+(index+1)+'. 최근 '+(c.vis-start)+'개 캔들 표시. '+(reveal?'미래 '+reveal+'개 캔들 공개.':'미래 구간 비공개.')+' 상승 빨강, 하락 파랑.');}
  function renderQuestion(){if(attempt.completedAt&&index>=3){showResult();return;}pick=null;reveal=0;revealing=false;$('dailyStart').hidden=true;$('dailyResult').hidden=true;$('dailyPlay').hidden=false;$('dailyIntro').hidden=true;$('challengeTitle').textContent=(practice?'연습':'첫 도전')+' · 다음 종가를 예측하세요';$('dailyProgress').textContent=(index+1)+' / 3';$('dailyDate').textContent=attempt.date+' · 한국 시간';$('dailyFeedback').hidden=true;$('dailyNext').hidden=true;$('dailyChoices').hidden=false;$('dailyConfirm').hidden=false;$('dailyConfirm').disabled=true;$('dailyConfirm').textContent='방향을 선택하세요';document.querySelectorAll('[data-pick]').forEach(function(b){b.disabled=false;b.setAttribute('aria-pressed','false');});var c=currentChart();if(!c){status('이 기록의 차트 데이터를 찾지 못했습니다. 새로고침해 주세요.');return;}$('dailyChartLabel').textContent=c.tf+' · 미래 '+(c.cs.length-c.vis)+'개 캔들 · 상승 빨강 / 하락 파랑';requestAnimationFrame(draw);}
  function showResult(){revealing=false;$('dailyIntro').hidden=true;$('dailyPlay').hidden=true;$('dailyStart').hidden=true;$('dailyResult').hidden=false;$('challengeTitle').textContent=practice?'연습 완료':'오늘의 첫 도전 완료';$('dailyScore').textContent=attempt.score+' / 300';$('dailyResultMode').textContent=practice?'연습 기록 · 첫 기록은 유지됩니다':cloud?'서버에 저장된 첫 도전':'이 기기에 저장된 첫 도전';$('dailyResultText').textContent=attempt.answers.filter(function(a){return a.correct;}).length+'문제 정답. 다른 판단이 필요했던 구간을 다시 살펴보세요.';$('dailyProgress').textContent='3 / 3 완료';$('dailyUpload').hidden=practice||cloud||window.CA_LOCAL_PREVIEW;$('dailyToday').hidden=attempt.date===R.day();if(!practice){reward().catch(function(){status('완료 기록은 저장했지만 꾸미기 보상을 저장하지 못했습니다. 저장 공간을 확인해 주세요.');});}}
  async function sync(wanted){if(wanted.date!==R.day())throw new Error('지난 날짜의 기록은 기기에만 보관합니다.');if(!db||!uid)throw new Error('서버에 연결되지 않았습니다.');var ref=db.collection('scores').doc(uid);return timeout(db.runTransaction(async function(tx){var snap=await tx.get(ref),data=snap.exists?snap.data():{},remote=data.dailyAttempt;if(remote&&remote.date>wanted.date)throw new Error('지난 날짜의 기록은 서버의 최신 기록을 바꾸지 않습니다.');if(remote&&remote.date!==wanted.date)remote=null;var canonical=R.reconcile(wanted,remote),patch={nick:nick,dailyDate:canonical.date,dailyScore:canonical.completedAt?canonical.score:-1,dailyAttempt:canonical};if(typeof data.points!=='number')patch.points=0;tx.set(ref,patch,{merge:true});return canonical;}));}
  async function saveFirst(next){var canonical=next;cloud=false;if(db&&uid){try{canonical=await sync(next);cloud=true;}catch(e){status('서버 동기화가 안 되어 기기에 먼저 저장합니다. 완료 후 다시 동기화할 수 있어요.');}}write(KEY+canonical.date,canonical);write(ACTIVE,canonical.date);return canonical;}
  async function start(){if(busy)return;if(!attempt)date=R.day();busy=true;$('dailyStartButton').disabled=true;try{await lock(KEY+date,async function(){var saved=read(KEY+date);attempt=saved||R.create(date,charts);attempt=await saveFirst(attempt);practice=false;index=attempt.answers.length;if(attempt.completedAt)showResult();else renderQuestion();});}catch(e){status('시작 기록을 저장하지 못했습니다. 브라우저 저장 공간을 확인한 뒤 다시 시도해 주세요.');$('dailyStartButton').disabled=false;}finally{busy=false;}}
  async function confirm(){if(busy||revealing||!pick)return;busy=true;$('dailyConfirm').disabled=true;document.querySelectorAll('[data-pick]').forEach(function(b){b.disabled=true;});var expected=index;try{if(practice){attempt=R.answer(attempt,index,pick,charts);}else{await lock(KEY+attempt.date,async function(){var latest=read(KEY+attempt.date)||attempt;if(latest.answers.length!==index||latest.completedAt){attempt=latest;return;}attempt=await saveFirst(R.answer(latest,index,pick,charts));});}if(attempt.answers.length!==expected+1){index=attempt.answers.length;if(attempt.completedAt)showResult();else renderQuestion();status('다른 탭 또는 서버의 먼저 저장된 기록을 불러왔습니다.');return;}await showReveal();}catch(e){status('답안을 저장하지 못해 공개를 멈췄습니다. 저장 공간과 연결을 확인한 뒤 다시 눌러 주세요.');$('dailyConfirm').disabled=false;document.querySelectorAll('[data-pick]').forEach(function(b){b.disabled=false;});}finally{busy=false;}}
  async function showReveal(){revealing=true;$('dailyChoices').hidden=true;$('dailyConfirm').hidden=true;var c=currentChart(),count=c.cs.length-c.vis,reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;for(var n=1;n<=count;n++){if(closed)return;reveal=n;draw();if(!reduce)await new Promise(function(resolve){setTimeout(resolve,n===count?350:55);});}revealing=false;var a=attempt.answers[index],o=R.outcome(c);$('dailyFeedback').hidden=false;$('dailyFeedback').textContent=(a.correct?'정답! +100점. ':'이번 구간은 반대 방향이었어요. ')+c.sym+' · '+c.period+' · 마지막 종가 '+(o.move>=0?'+':'')+o.move.toFixed(2)+'%. '+(c.explain||'현재 종가와 공개된 마지막 종가를 비교한 결과입니다.');$('dailyNext').textContent=index===2?'도전 결과 보기':'다음 차트';$('dailyNext').hidden=false;if(!practice&&attempt.completedAt)await reward();}
  function loadScript(src){return new Promise(function(resolve,reject){var s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}
  async function connect(){if(window.CA_LOCAL_PREVIEW){status('로컬 미리보기 · 이 기기에만 도전 기록을 저장합니다.');return;}await timeout((async function(){for(var module of ['app','auth','firestore'])if(!window.firebase||(module!=='app'&&!firebase[module]))await loadScript('https://www.gstatic.com/firebasejs/10.12.2/firebase-'+module+'-compat.js');if(!firebase.apps.length)firebase.initializeApp({apiKey:'AIzaSyCRGFwkDNEIkTc7mnPPqiubFDaTjWf87iA',authDomain:'chartarena-3051a.firebaseapp.com',projectId:'chartarena-3051a',appId:'1:44830019146:web:76089575110b3107e460b3'});var credential=await firebase.auth().signInAnonymously();uid=credential.user.uid;db=firebase.firestore();})());}
  async function ranking(){if(!db){$('dailyRankingStatus').textContent=window.CA_LOCAL_PREVIEW?'로컬 미리보기에서는 온라인 기록을 불러오지 않습니다.':'오프라인 · 서버 기록을 불러오지 못했습니다.';return;}$('dailyRankingStatus').textContent='오늘의 기록을 불러오는 중…';try{var qs=await timeout(db.collection('scores').where('dailyDate','==',R.day()).get()),rows=[];qs.forEach(function(doc){var d=doc.data();if(d.dailyAttempt&&d.dailyAttempt.date===R.day()&&d.dailyAttempt.completedAt&&Number.isFinite(d.dailyScore)&&d.dailyScore>=0&&d.dailyScore<=300)rows.push({id:doc.id,nick:String(d.nick||'도전자'),score:d.dailyScore});});rows.sort(function(a,b){return b.score-a.score||a.id.localeCompare(b.id);});$('dailyRanking').replaceChildren();var rank=0;rows.forEach(function(row,i){if(!i||row.score!==rows[i-1].score)rank=i+1;var li=document.createElement('li'),name=document.createElement('span'),score=document.createElement('b');name.textContent=rank+'위 · '+row.nick+(row.id===uid?' (나)':'');score.textContent=row.score+'점';li.append(name,score);$('dailyRanking').append(li);});$('dailyRankingStatus').textContent=rows.length?rows.length+'명의 첫 도전 기록':'아직 등록된 기록이 없습니다. 첫 도전을 남겨보세요.';}catch(e){$('dailyRankingStatus').textContent='기록을 불러오지 못했습니다. 잠시 후 새로고침해 주세요.';}}
  async function init(){renderRewards();$('dailyDate').textContent=date+' · 한국 시간';try{await connect();if(db){var snap=await timeout(db.collection('scores').doc(uid).get()),remote=snap.exists?snap.data().dailyAttempt:null;if(remote&&remote.date===date){write(KEY+date,remote);cloud=true;}status('첫 도전은 같은 브라우저 계정의 서버 기록과 함께 저장됩니다.');}}catch(e){db=null;uid=null;status('서버 기록을 확인하지 못했습니다. 기기 기록으로 진행하며, 서버 연결 후 기존 첫 기록이 우선됩니다.');}var saved=read(KEY+date);if(saved&&saved.version===R.VERSION){attempt=saved;index=saved.answers.length;if(saved.completedAt)showResult();else{status('저장된 첫 도전 '+saved.answers.length+' / 3문제부터 이어갑니다.');renderQuestion();}}else{$('dailyStartButton').disabled=false;$('dailyStartButton').textContent='오늘의 첫 도전 시작';}ranking();}
  document.querySelectorAll('[data-pick]').forEach(function(b){b.onclick=function(){if(busy||revealing)return;pick=b.dataset.pick;document.querySelectorAll('[data-pick]').forEach(function(x){x.setAttribute('aria-pressed',String(x===b));});$('dailyConfirm').disabled=false;$('dailyConfirm').textContent='선택 확정 · 다음 구간 공개';};});
  $('dailyStartButton').onclick=start;$('dailyConfirm').onclick=confirm;$('dailyNext').onclick=function(){if(busy||revealing)return;index++;if(index===3){showResult();ranking();}else renderQuestion();};
  $('dailyPractice').onclick=function(){practice=true;attempt=R.create(attempt.date,charts);index=0;renderQuestion();status('연습 모드 · 첫 기록과 컬렉션 보상은 그대로 유지됩니다.');};
  $('dailyRefresh').onclick=async function(){$('dailyRefresh').disabled=true;try{if(!db)await connect();await ranking();}catch(e){$('dailyRankingStatus').textContent='서버 연결이 안 됩니다. 잠시 후 다시 시도해 주세요.';}finally{$('dailyRefresh').disabled=false;}};
  $('dailyUpload').onclick=async function(){if(busy||practice)return;busy=true;$('dailyUpload').disabled=true;try{if(!db)await connect();await lock(KEY+attempt.date,async function(){var saved=read(KEY+attempt.date)||attempt;attempt=await sync(saved);write(KEY+attempt.date,attempt);cloud=true;index=attempt.answers.length;});if(attempt.completedAt)showResult();else renderQuestion();status('서버의 첫 기록과 동기화했습니다. 이미 존재하는 첫 답안은 유지됩니다.');await ranking();}catch(e){status('서버 동기화를 완료하지 못했습니다. 기기에 저장된 기록은 유지됩니다.');}finally{busy=false;$('dailyUpload').disabled=false;}};
  $('dailyToday').onclick=function(){location.reload();};
  window.addEventListener('resize',draw);window.addEventListener('pagehide',function(){closed=true;});window.addEventListener('storage',function(e){if(e.key===REWARDS)renderRewards();if(attempt&&!practice&&e.key===KEY+attempt.date&&!busy&&!revealing){var saved=read(e.key);if(saved&&saved.answers.length>attempt.answers.length){attempt=saved;index=saved.answers.length;if(saved.completedAt)showResult();else renderQuestion();status('다른 탭에서 저장한 첫 도전 기록을 이어갑니다.');}}});
  init().catch(function(){status('도전을 준비하지 못했습니다. 새로고침해 주세요.');});
})();
