const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../battle-rules.js');
test('match capital is equal and independent from persistent gold',()=>{assert.equal(R.create('a').balance,10000);assert.equal(R.create('b').balance,10000);});
test('power and defense affect both gains and losses, once per match',()=>{for(const move of [10,-10]){const base=R.settle(R.create('a'),{dir:'L',risk:'normal'},move,1);const power=R.settle(R.create('a'),{dir:'L',risk:'normal',power:'push'},move,1);const defense=R.settle(R.create('a'),{dir:'L',risk:'normal',power:'guard'},move,1);assert.equal(power.delta,base.delta*1.5);assert.equal(defense.delta,base.delta*.5);assert.equal(R.choice(power,{dir:'L',power:'guard'}).power,'none');}});
test('deliberate pass is free once; timeout is distinct and does not spend it',()=>{let p=R.settle(R.create('a'),{dir:'W'},40,1);assert.equal(p.delta,0);assert.equal(p.passUsed,true);p=R.settle(p,{dir:'W'},40,2);assert.equal(p.pick.dir,'N');assert.equal(p.delta,-200);let n=R.settle(R.create('b'),null,40,1);assert.equal(n.passUsed,false);assert.equal(n.delta,-200);});
test('loss capped to the actual stake even with power',()=>{let p=R.settle(R.create('a'),{dir:'S',risk:'bold',power:'push'},500,1);assert.equal(p.balance,5000);assert.equal(p.delta,-5000);});
test('duplicate and stale results cannot pay or consume twice',()=>{let p=R.settle(R.create('a'),{dir:'L',power:'push'},10,1);assert.deepEqual(R.settle(p,{dir:'S'},-10,1),p);assert.throws(()=>R.settle(p,{dir:'L'},10,3));});
test('host and guest ordering produce identical scores by player id',()=>{let a=R.create('a'),b=R.create('b'),picks={a:{dir:'S',risk:'careful'},b:{dir:'L',risk:'bold'}};const settle=ps=>Object.fromEntries(ps.map(p=>{const n=R.settle(p,picks[p.id],3,1);return [p.id,n.balance];}));assert.deepEqual(settle([a,b]),settle([b,a]));});
test('invalid input is normalized and final rewards respect ties',()=>{const p=R.create('a');assert.equal(R.choice(p,{dir:'BAD',betPct:999}).dir,'N');assert.equal(R.choice(p,{dir:'L',advanced:true,betPct:999,lev:Infinity}).betPct,.25);assert.equal(R.rank([{id:'a',score:4},{id:'b',score:4},{id:'c',score:0}],'b'),1);assert.equal(R.reward(1),2000);});
