const {chromium}=(()=>{try{return require('playwright');}catch(_){return require(require('node:path').join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}})();
const assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.CHARTARENA_URL||'http://127.0.0.1:8035/',key='chartarena_club_tour_v1',errors=[],checks=[];
const fixture=()=>{const cs=Array.from({length:300},(_,i)=>{const v=100+Math.max(0,i-209)*.01;return[v,v+.002,v-.002,v];});BATTLE_CHARTS.forEach(s=>s.cs=cs);};
const saved=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
async function reach(p,selector){for(let i=0;i<160;i++){if(await p.locator(selector).isVisible())return;await p.clock.fastForward(500);await p.waitForTimeout(15);}throw Error('Missing '+selector);}
(async()=>{
 fs.mkdirSync('exports',{recursive:true});
 const browser=await chromium.launch({headless:true});
 async function tour(character='tr_taeo',viewport={width:390,height:844}){const context=await browser.newContext({viewport});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-21T12:00:00Z')});await p.clock.pauseAt(new Date('2026-09-21T12:00:01Z'));await p.goto(base+'club-tour.html',{waitUntil:'networkidle'});await p.evaluate(fixture);await p.locator('[data-tour-character="'+character+'"]').click();return{p,context};}
 {
  const{p,context}=await tour('tr_chaerin');await p.locator('#tourStart').click();await p.locator('[data-tour-dir="L"]').click();await p.locator('[data-tour-lev="2"]').click();await p.locator('#tourConfirm').click();await p.locator('#tourDirection').waitFor({state:'hidden'});await reach(p,'#tourDecisions:not([hidden])');await p.locator('[data-tour-action="SWITCH"]').click();await p.locator('[data-tour-lev="5"]').click();await p.locator('#tourSignature').check();await p.screenshot({path:'exports/royal-play-tour-switch-390.png',fullPage:true});await p.locator('#tourConfirm').click();await p.locator('#tourDecisions').waitFor({state:'hidden'});let s=await saved(p);assert.equal(s.signatureAt,30);assert.deepEqual(s.picks.me.leverageChanges,[{at:30,lev:5}]);
  await reach(p,'#tourDecisions:not([hidden])');assert.equal(await p.locator('#tourSignature').isDisabled(),true);await p.locator('[data-tour-action="STOP"]').click();await p.locator('#tourConfirm').click();await p.locator('#tourDecisions').waitFor({state:'hidden'});await reach(p,'#tourOutcome:not([hidden])');s=await saved(p);assert.equal(s.phase,'lost');assert.equal(s.history[0].steps.length,2);await p.locator('[data-tour-review]').click();assert.deepEqual(await p.locator('.review-ledger tbody tr td:nth-child(2)').allTextContents(),['롱 2배','숏 5배']);await p.screenshot({path:'exports/royal-play-tour-review-390.png'});checks.push('Chaerin SWITCH 2→5 signature, STOP, loss and exact review');await context.close();
 }
 {
  const{p,context}=await tour();await p.locator('#tourStart').click();await p.locator('[data-tour-dir="S"]').click();await p.locator('[data-tour-lev="10"]').click();await p.locator('#tourSignature').check();await p.locator('#tourConfirm').click();await p.locator('#tourDirection').waitFor({state:'hidden'});await reach(p,'#tourDecisions:not([hidden])');assert.equal((await saved(p)).scores.me,-1000);
  const deadline=(await saved(p)).deadline;await p.reload({waitUntil:'networkidle'});await p.evaluate(fixture);await p.clock.fastForward(16000);await p.locator('#tourResume').click();await p.clock.fastForward(150);await p.locator('#tourDecisions').waitFor({state:'hidden'});assert.equal((await saved(p)).picks.me.exit,30);assert.ok(await p.evaluate(d=>Date.now()>=d,deadline));await reach(p,'#tourOutcome:not([hidden])');assert.equal((await saved(p)).scores.me,-1000);checks.push('Taeo loss cap, saved deadline reload, auto STOP preserves loss');await context.close();
 }
 {
  const{p,context}=await tour();await p.evaluate(()=>{const T=ClubTourRules,cs=BATTLE_CHARTS[0].cs;let s=T.create('guard-miss','tr_taeo',[0,1,2],Date.now());s=T.commit(s,{dir:'L',lev:3},{dir:'S',lev:1},Date.now());for(let i=0;i<3;i++){s=T.reveal(s,cs,Date.now());if(i<2)s=T.commit(s,{action:'GO'},{action:'GO'},Date.now());}s=T.choose(s,'guard',Date.now());localStorage.setItem('chartarena_club_tour_v1',JSON.stringify(s));});await p.reload({waitUntil:'networkidle'});await p.evaluate(fixture);await p.locator('#tourResume').click();await p.clock.fastForward(16000);await p.locator('#tourDirection').waitFor({state:'hidden'});assert.equal((await saved(p)).picks.me.dir,'N');await reach(p,'#tourOutcome:not([hidden])');const s=await saved(p);assert.equal(s.scores.me,-1000);assert.deepEqual(s.history[1].steps,[]);await p.locator('[data-tour-review]').click();await p.locator('[data-round="1"]').click();assert.match(await p.locator('.review-empty').innerText(),/1,000점/);assert.equal(await p.evaluate(()=>localStorage.getItem('chartarena_web_v1')),null);checks.push('Guard does not reduce missed entry fee; auto observation and PT receipt');await context.close();
 }
 {
  const{p,context}=await tour();await p.locator('#tourStart').click();await p.locator('#tourGame').waitFor({state:'visible'});const q=await context.newPage();q.on('pageerror',e=>errors.push(e.message));await q.clock.install({time:new Date('2026-09-21T12:00:01Z')});await q.clock.pauseAt(new Date('2026-09-21T12:00:01Z'));await q.goto(base+'club-tour.html',{waitUntil:'networkidle'});await q.evaluate(fixture);await q.locator('#tourResume').click();await q.locator('[data-tour-dir="L"]').click();await q.locator('#tourConfirm').click();await q.locator('#tourDirection').waitFor({state:'hidden'});await p.locator('#tourLobby').waitFor({state:'visible'});assert.match(await p.locator('#tourNotice').innerText(),/다른 창/);assert.deepEqual(await saved(p),await saved(q));checks.push('Two tabs preserve newest revision and retire stale controls');await context.close();
 }
 {
  const context=await browser.newContext({reducedMotion:'reduce'});await context.addInitScript(()=>{window.__audioCount=0;const C=window.AudioContext||window.webkitAudioContext;if(C){const original=C.prototype.createOscillator;C.prototype.createOscillator=function(...a){window.__audioCount++;return original.apply(this,a);};}});const p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'club-tour.html',{waitUntil:'networkidle'});await p.locator('[data-tour-character="tr_taeo"]').click();await p.waitForTimeout(150);await p.evaluate(()=>ArenaFeedback.play('confirm'));await p.waitForTimeout(150);assert.ok(await p.evaluate(()=>__audioCount>0));await p.locator('[data-arena-sound]').click();const count=await p.evaluate(()=>__audioCount);await p.evaluate(()=>ArenaFeedback.pulse(document.querySelector('.tour-poster'),'switch'));assert.equal(await p.locator('.choice-feedback').count(),0);assert.equal(await p.evaluate(()=>__audioCount),count);await p.reload({waitUntil:'networkidle'});assert.equal(await p.locator('[data-arena-sound]').getAttribute('aria-pressed'),'false');await p.locator('[data-arena-sound]').click();await p.waitForTimeout(150);await p.evaluate(()=>ArenaFeedback.play('win'));assert.ok(await p.evaluate(()=>__audioCount>0));checks.push('Audio gesture, mute persistence, re-enable and reduced-motion fallback');await context.close();
 }
 assert.deepEqual(errors,[]);fs.writeFileSync('exports/royal-play-edge-qa.json',JSON.stringify({checks,errors},null,2));console.log('PASS: '+checks.join('; '));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
