const test=require('node:test');const assert=require('node:assert/strict');const R=require('../daily-rules.js');
const charts=Array.from({length:20},(_,i)=>({id:'chart-'+i,vis:12,cs:Array.from({length:20},(_,j)=>[100,120,80,j<12?100:100+(i%2?10:-10)])}));
test('daily date rolls over at midnight in Korea, independent of host timezone',()=>{assert.equal(R.day('2026-09-18T14:59:59Z'),'2026-09-18');assert.equal(R.day('2026-09-18T15:00:00Z'),'2026-09-19');});
test('unfinished first attempt resumes its original date after midnight; completed attempt opens the new date',()=>{let a=R.create('2026-09-18',charts,1);a=R.answer(a,0,'L',charts,2);assert.equal(R.resumeDate('2026-09-19',JSON.parse(JSON.stringify(a))),'2026-09-18');for(let i=1;i<3;i++)a=R.answer(a,i,'S',charts,3+i);assert.equal(R.resumeDate('2026-09-19',a),'2026-09-19');});
test('all players receive three unique versioned deterministic questions irrespective of source order',()=>{const a=R.questions('2026-09-19',charts).map(c=>c.id),b=R.questions('2026-09-19',charts.slice().reverse()).map(c=>c.id);assert.deepEqual(a,b);assert.equal(new Set(a).size,3);assert.notDeepEqual(a,R.questions('2026-09-20',charts).map(c=>c.id));});
test('reload resumes stored answers, duplicate confirmations do not rescore, completed first attempt is immutable',()=>{let a=R.create('2026-09-19',charts,1);a=R.answer(a,0,'L',charts,2);const reload=JSON.parse(JSON.stringify(a));assert.equal(reload.answers.length,1);assert.strictEqual(R.answer(reload,0,'S',charts),reload);a=R.answer(reload,1,'S',charts,3);a=R.answer(a,2,'L',charts,4);assert.equal(a.completedAt,4);assert.strictEqual(R.answer(a,2,'S',charts),a);assert.equal(a.score,a.answers.filter(x=>x.correct).length*100);});
test('practice is a separate attempt and cannot change original answers or score',()=>{let first=R.create('2026-09-19',charts,1);for(let i=0;i<3;i++)first=R.answer(first,i,'L',charts,2+i);const snapshot=JSON.stringify(first);let practice=R.create(first.date,charts,6);practice=R.answer(practice,0,'S',charts,7);assert.equal(JSON.stringify(first),snapshot);assert.equal(practice.answers.length,1);});
test('server first answers win a conflict and may only extend matching answer prefixes',()=>{const base=R.create('2026-09-19',charts,1),remote=R.answer(base,0,'L',charts,2),local=R.answer(base,0,'S',charts,3);assert.strictEqual(R.reconcile(local,remote),remote);const extension=R.answer(remote,1,'L',charts,4);assert.strictEqual(R.reconcile(extension,remote),extension);assert.strictEqual(R.reconcile(remote,extension),extension);});
test('unique completion days unlock cosmetics idempotently without practice rewards',()=>{let r=R.rewards(null,'2026-09-19');r=R.rewards(r,'2026-09-19');assert.equal(r.days.length,1);assert.deepEqual(r.unlockedFrames,['none','blue']);for(let i=20;i<=25;i++)r=R.rewards(r,'2026-09-'+i);assert.equal(r.days.length,7);assert.ok(r.unlockedFrames.includes('gold'));assert.ok(r.unlockedPoses.includes('celebrate'));});
function server(initial){const fs=require('node:fs'),vm=require('node:vm'),src=fs.readFileSync(require.resolve('../daily.js'),'utf8');let data=initial,patches=[];const context={R:{...R,day:()=> '2026-09-19'},uid:'existing-user',nick:'도전자',timeout:p=>p,db:{collection:()=>({doc:()=> 'scores/existing-user'}),runTransaction:async fn=>fn({get:async()=>({exists:!!data,data:()=>data}),set:(_ref,patch,options)=>{assert.equal(options.merge,true);patches.push(patch);data={...data,...patch};}})}};vm.createContext(context);vm.runInContext(src.slice(src.indexOf('async function sync(wanted){'),src.indexOf('async function saveFirst(next){')),context);return {sync:context.sync,patches,get data(){return data;}};}
test('server upload preserves existing balance and accepts only completed first score for ranking',async()=>{const s=server({points:987654,nick:'기존',played:9});let a=R.create('2026-09-19',charts,1);await s.sync(a);assert.equal(s.data.dailyScore,-1);assert.equal(s.data.points,987654);assert.equal('points' in s.patches[0],false);for(let i=0;i<3;i++)a=R.answer(a,i,'L',charts,2+i);await s.sync(a);assert.equal(s.data.dailyScore,a.score);assert.equal(s.data.played,9);});
test('second-tab alternate completed score cannot overwrite the server first completion',async()=>{let first=R.create('2026-09-19',charts,1),other=R.create('2026-09-19',charts,2);for(let i=0;i<3;i++){first=R.answer(first,i,'L',charts,3+i);other=R.answer(other,i,'S',charts,6+i);}const s=server({points:500,dailyAttempt:first});const result=await s.sync(other);assert.deepEqual(result,first);assert.equal(s.data.dailyScore,first.score);});
test('old-day attempt never writes to the server after the Korean day boundary',async()=>{const s=server({points:500});await assert.rejects(s.sync(R.create('2026-09-18',charts,1)));assert.equal(s.patches.length,0);});
