const {chromium}=(()=>{try{return require('playwright');}catch(_){return require(require('node:path').join(require('node:os').homedir(),'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));}})();
const assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{
 fs.mkdirSync('exports',{recursive:true});
 const b=await chromium.launch({headless:true}),c=await b.newContext(),p=await c.newPage(),errors=[],layouts=[];
 p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-09-21T10:00:00Z')});await p.clock.pauseAt(new Date('2026-09-21T10:00:01Z'));
 await c.addInitScript(()=>{if(!localStorage.getItem('qa-seeded')){localStorage.setItem('chartarena_hub_v1',JSON.stringify({nick:'레이아웃테스터',equip:{ch:'tr_sera'},setup:true,owned:{char:['tr_sera']},gems:100}));localStorage.setItem('chartarena_web_v1',JSON.stringify({balance:100000000}));localStorage.setItem('qa-seeded','1');}sessionStorage.setItem('ca_club_intro_v2_b','1');sessionStorage.setItem('ca_club_intro_v2','1');});
 await p.goto((process.env.CHARTARENA_URL||'http://127.0.0.1:8035/')+'index.html',{waitUntil:'networkidle'});await p.clock.fastForward(8000);if(await p.locator('#dpop .dbtn').isVisible())await p.locator('#dpop .dbtn').click();else if(await p.getByRole('button',{name:'받기',exact:true}).isVisible())await p.getByRole('button',{name:'받기',exact:true}).click();
 await p.clock.fastForward(2500);
 for(const [width,height] of [[320,650],[390,844],[667,375],[960,720]]){await p.setViewportSize({width,height});await p.screenshot({path:`exports/royal-play-home-${width}.png`,fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'home overflow '+width);const bounds=await p.evaluate(()=>({sound:document.querySelector('[data-arena-sound]').getBoundingClientRect().toJSON(),top:document.querySelector('.topbar').getBoundingClientRect().toJSON(),mastery:document.querySelector('#characterMastery').getBoundingClientRect().toJSON(),showcase:document.querySelector('.arena-showcase').getBoundingClientRect().toJSON(),curr:document.querySelector('.curr').getBoundingClientRect().toJSON()}));assert.ok(bounds.curr.right<=width,'currencies contained '+width);assert.ok(bounds.sound.bottom<=bounds.top.bottom+1,'sound contained '+width);assert.ok(bounds.mastery.bottom<=bounds.showcase.bottom+1,'mastery contained '+width);}
 await p.setViewportSize({width:1440,height:900});await p.goto((process.env.CHARTARENA_URL||'http://127.0.0.1:8035/')+'quiz-battle.html?table=standard',{waitUntil:'networkidle'});await p.locator('#modeLive').click();for(let i=0;i<50&&!await p.locator('#dL:enabled').isVisible();i++){await p.clock.fastForward(500);await p.waitForTimeout(20);}await p.locator('#dL').click();
 for(const [width,height] of [[320,650],[390,844],[667,375],[960,720]]){await p.setViewportSize({width,height});await p.screenshot({path:`exports/royal-play-battle-${width}.png`});const layout=await p.evaluate(()=>({width:innerWidth,height:innerHeight,overflow:document.documentElement.scrollWidth>innerWidth,buttons:['dL','dS','dW','go'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{id,x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};})}));layouts.push(layout);assert.equal(layout.overflow,false);assert.ok(layout.buttons.every(r=>r.x>=0&&r.right<=width&&r.y>=0&&r.bottom<=height&&r.height>=44),'play controls '+width);}
 assert.deepEqual(errors,[]);fs.writeFileSync('exports/royal-layout-qa.json',JSON.stringify({layouts,errors},null,2));console.log('PASS: 4 responsive home/battle sizes and visible touch controls');await b.close();
})().catch(e=>{console.error(e);process.exit(1)});
