const fs = require('node:fs');
const crypto = require('node:crypto');
const versions = Object.fromEntries(['royal-play.css', 'royal-experience.js', 'battle-review.js', 'battle-review.css', 'character-mastery.js', 'arena-feedback.js', 'club-tour-rules.js', 'club-tour.js', 'club-tour.css', 'room-cards.css', 'royal-gold.css', 'battle-rivals.js', 'battle-presentation.js', 'battle-presentation.css', 'arena-social.js', 'social-config.js', 'arena-auth.js', 'login.js', 'login.css', 'battle-controls.css', 'arena-motion.js', 'arena-wallet.js', 'deathmatch.js', 'deathmatch.css', 'deathmatch-rules.js', 'arena-reactions.js', 'arena-reactions.css', 'battle-charts.js', 'battle-data.js', 'arena-design.css', 'arena-characters.js', 'terminal-home.css', 'terminal-home.js', 'exchange-theme.css', 'battle-fx.js', 'battle-fx.css', 'energy.js', 'app-shell.js', 'app-shell.css', 'battle-rules.js', 'gameplay.css', 'puzzle-rules.js', 'daily.js', 'daily-rules.js'].map(file =>
  [file, crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').slice(0, 12)]));
for (const page of fs.readdirSync('.').filter(p => p.endsWith('.html'))) {
  const html = fs.readFileSync(page, 'utf8');
  const updated = html.replace(/((?:src|href)=")(royal-play\.css|royal-experience\.js|battle-review\.js|battle-review\.css|character-mastery\.js|arena-feedback\.js|club-tour-rules\.js|club-tour\.js|club-tour\.css|room-cards\.css|royal-gold\.css|arena-auth\.js|arena-social\.js|social-config\.js|login\.js|login\.css|battle-rivals\.js|battle-presentation\.js|battle-presentation\.css|battle-controls\.css|arena-motion\.js|arena-wallet\.js|deathmatch\.js|deathmatch\.css|deathmatch-rules\.js|arena-reactions\.js|arena-reactions\.css|battle-charts\.js|battle-data\.js|arena-design\.css|arena-characters\.js|terminal-home\.css|terminal-home\.js|exchange-theme\.css|battle-fx\.js|battle-fx\.css|energy\.js|app-shell\.js|app-shell\.css|battle-rules\.js|gameplay\.css|puzzle-rules\.js|daily\.js|daily-rules\.js)(?:\?[^\"]*)?"/g,
    (_, prefix, file) => prefix + file + '?v=' + versions[file] + '"');
  if (updated !== html) fs.writeFileSync(page, updated.replace(/\r\n/g, '\n'));
}
console.log('Shared runtime content versions updated.');
